FROM registry.access.redhat.com/ubi8/openjdk-17:1.14

EXPOSE 8080
EXPOSE 443

COPY simple-server/target/simple-server-1.0.0-SNAPSHOT-runner.jar /deployments/quarkus-run.jar

USER 185

ENV QUARKUS_PROFILE=plain
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"
